
<p style="text-align: left;"><img src="https://upload.wikimedia.org/wikipedia/commons/6/63/CNE_logo.svg" alt="cne" width="134" height="89" />&nbsp;&nbsp;&nbsp; <img style="float: right;" src="http://res.cloudinary.com/tuconsultaenlinea/image/upload/v1510595868/CREDENCIAL_TESTIGO_JUNTA_REGIONAL_2017_html_d3a220d6_jt12xm.png" alt="" width="129" height="76" /></p>
<p style="line-height: 1.3800000000000001; margin-top: 0pt; margin-bottom: 10pt; text-align: center;"><span style="font-family: courier new,courier;"><strong><span style="font-size: 20pt; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline;">ELECCIONES REGIONALES 2017</span></strong></span></p>
<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-family: courier new,courier;"><strong><span style="font-size: 18pt; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline;">CREDENCIAL</span></strong></span></p>
<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: center;">&nbsp;</p>
<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: center;"><span style="font-family: courier new,courier;"><strong><span style="font-size: 18pt; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline;">TESTIGO ANTE LA JUNTA REGIONAL ELECTORAL</span></strong></span></p>
<p style="line-height: 1.2; margin-top: 0pt; margin-bottom: 0pt; text-align: center;">&nbsp;</p>
<p style="padding-left: 60px; text-align: justify;">El Consejo Nacional Electoral, en uso de las atribuciones que le confiere el art&iacute;culo 33 numeral 13 de la Ley Org&aacute;nica del Poder Electoral, acredita a la ciudadana o ciudadano: <label style="text-decoration: underline;"><?php echo $testigo->nombre ?> <?php echo $testigo->apellido ?></label>, titular de la c&eacute;dula de identidad N&deg; <label style="text-decoration: underline;"><?php echo $testigo->cedula ?></label>, como Testigo Principal ante la Junta Regional Electoral de la Entidad: <label style="text-decoration: underline;"><?php echo $ubch->nombre_ubch ?></label>, ubicada en: <label style="text-decoration: underline;"><?php echo $ubch->direccion_ubch ?></label>. Designado por la Organizaci&oacute;n con Fines Pol&iacute;ticos: ___________________________________, con motivo de las Elecciones Regionales a celebrarse el 15 de octubre de 2017.</p>
<p style="padding-left: 60px; text-align: justify;">Dada en la ciudad de <?php echo $ubch->municipio->nombre ?> a los <?php echo date('d') ?> d&iacute;as del mes de <?php echo date('M') ?> de 2017</p>

<p style="padding-left: 60px; text-align: justify;"><img src="http://res.cloudinary.com/tuconsultaenlinea/image/upload/v1510595867/CREDENCIAL_TESTIGO_JUNTA_REGIONAL_2017_html_4fbc4f1b_xmzjun.jpg" alt="firma" width="459" height="234" /><strong><span style="font-family: calibri,sans-serif;">Junta Regional Electoral</span></strong></p>
<p style="padding-left: 60px; text-align: center;"><strong><span style="font-family: calibri,sans-serif;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <em>firma sello</em></span> </strong></p>
<p style="padding-left: 60px; text-align: center;"><strong><em><span style="font-size: 9pt; font-family: Cabin; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline;">La presente credencial es v&aacute;lida si est&aacute; firmada y sellada por el Consejo Nacional Electoral y por la Junta Regional Electoral correspondiente, sin tachaduras ni enmendaduras, y es aval suficiente para tramitar el permiso laboral correspondiente.</span></em></strong></p>
<p style="padding-left: 60px; text-align: center;"><span style="background-color: #dedede; color: #000000;"><strong><span style="font-size: 14pt; font-family: Cabin; font-variant: normal; text-decoration: none; vertical-align: baseline; background-color: #dedede;">No se permitir&aacute; en un mismo acto electoral, m&aacute;s de un (1) testigo por alianza.</span></strong></span></p>
